openapi: "3.0.0"
info:
  title: TODO API Document
  version: "0.0.1"
paths:
  /tasks/:
    get:
      tags:
        - "tasks"
      summary: "タスク一覧取得"
      description: "タスクの一覧を取得できます"
      operationId: listTasks
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskListDTO"
    post:
      tags:
        - "tasks"
      summary: "タスク作成"
      description: "タスクを新規作成します" 
      operationId: "createTask"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskForm"
      responses:
        201:
          description: "Created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDTO"
  /tasks/{id}:
    delete:
      tags:
        - "tasks"
      summary: "タスク削除"
      description: "指定したタスクを削除します"
      operationId: "delete"
      parameters:
        - name: id
          in: path
          required: true
          description: "更新するタスクのID"
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: "No Content"
        
components:
  schemas:
    TaskForm:
      type: object
      properties:
        id:
          type: integer
          description: "ID"
        text:
          type: string
          description: "テキスト"
      required:
        - text
    TaskDTO:
      type: object
      properties:
        id:
          type: integer
          description: "ID"
        text:
          type: string
          description: "テキスト"
      required:
        - id
        - text
    TaskListDTO:
      description: "タスクのリスト"
      type: array
      items:
        $ref: "#/components/schemas/TaskDTO"

